import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Empty, ui } from '@/components/UI';
import { colors } from '@/constants/theme';
import { formatDate, today } from '@/lib/date';
import { useApp } from '@/store/AppContext';

export default function Home() {
  const { currentUser, jobs, schedules, users } = useApp(); if (!currentUser) return null;
  const visibleJobs = currentUser.role === 'admin' ? jobs : jobs.filter((j) => j.workerIds.includes(currentUser.id));
  const upcoming = schedules.filter((s) => visibleJobs.some((j) => j.id === s.jobId) && s.endDate >= today()).sort((a,b) => a.startDate.localeCompare(b.startDate)).slice(0, 3);
  return <ScrollView style={ui.screen} contentContainerStyle={ui.content}><View><Text style={styles.hello}>{currentUser.name}님, 안녕하세요 👋</Text><Text style={ui.subtitle}>{currentUser.role === 'admin' ? '오늘의 작업 현황을 확인하세요.' : '배정된 작업과 일정을 확인하세요.'}</Text></View><View style={styles.stats}><Card style={styles.stat}><Text style={styles.statNumber}>{visibleJobs.length}</Text><Text style={styles.statLabel}>{currentUser.role === 'admin' ? '전체 작업' : '배정 작업'}</Text></Card><Card style={styles.stat}><Text style={styles.statNumber}>{currentUser.role === 'admin' ? users.filter(u => u.role === 'worker').length : upcoming.length}</Text><Text style={styles.statLabel}>{currentUser.role === 'admin' ? '작업자' : '예정 일정'}</Text></Card></View><Text style={ui.sectionTitle}>다가오는 일정</Text>{upcoming.length ? upcoming.map((item) => { const job = jobs.find(j => j.id === item.jobId); return <Pressable key={item.id} onPress={() => router.push(`/job/${item.jobId}`)}><Card style={styles.schedule}><View style={styles.dateBox}><Text style={styles.dateMonth}>{item.startDate.slice(5,7)}월</Text><Text style={styles.dateDay}>{item.startDate.slice(8,10)}</Text></View><View style={{ flex: 1 }}><Text style={styles.scheduleTitle}>{item.title}</Text><Text style={styles.meta}>{job?.title}</Text><Text style={styles.meta}>{formatDate(item.startDate)} ~ {formatDate(item.endDate)}</Text></View><Text style={styles.chevron}>›</Text></Card></Pressable>; }) : <Empty title="예정된 일정이 없습니다" detail="작업 상세에서 새 일정을 등록해보세요." />}</ScrollView>;
}
const styles = StyleSheet.create({ hello: { fontSize: 24, fontWeight: '800', color: colors.ink, marginBottom: 6 }, stats: { flexDirection: 'row', gap: 12 }, stat: { flex: 1 }, statNumber: { fontSize: 28, fontWeight: '800', color: colors.primary }, statLabel: { color: colors.muted, marginTop: 3 }, schedule: { flexDirection: 'row', alignItems: 'center', gap: 14 }, dateBox: { width: 52, height: 58, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, dateMonth: { fontSize: 11, color: colors.primary, fontWeight: '700' }, dateDay: { fontSize: 20, color: colors.primaryDark, fontWeight: '800' }, scheduleTitle: { color: colors.ink, fontSize: 16, fontWeight: '700', marginBottom: 4 }, meta: { color: colors.muted, fontSize: 12, marginTop: 2 }, chevron: { color: '#98A2B3', fontSize: 26 } });
