import { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Redirect } from 'expo-router';
import { Button, Card, Empty, Field, ui } from '@/components/UI';
import { colors } from '@/constants/theme';
import { useApp } from '@/store/AppContext';

export default function Workers() {
  const { currentUser, users, jobs, addWorker } = useApp(); const [open, setOpen] = useState(false); const [loginId, setLoginId] = useState(''); const [name, setName] = useState(''); const [password, setPassword] = useState('0000');
  if (!currentUser || currentUser.role !== 'admin') return <Redirect href="/(tabs)" />; const workers = users.filter(u => u.role === 'worker');
  const submit = async () => { if (!loginId.trim() || !name.trim() || !password) return Alert.alert('확인', '필수 항목을 입력해주세요.'); const error = await addWorker({ loginId, name, password }); if (error) return Alert.alert('확인', error); setLoginId(''); setName(''); setPassword('0000'); setOpen(false); };
  return <><ScrollView style={ui.screen} contentContainerStyle={ui.content}><View style={[ui.row, { justifyContent: 'space-between' }]}><View><Text style={ui.title}>작업자</Text><Text style={ui.subtitle}>{workers.length}명이 등록되어 있습니다.</Text></View><Pressable onPress={() => setOpen(true)} style={styles.add}><Text style={styles.addText}>＋ 추가</Text></Pressable></View>{workers.length ? workers.map(worker => <Card key={worker.id} style={styles.worker}><View style={styles.avatar}><Text style={styles.avatarText}>{worker.name.slice(0,1)}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{worker.name}</Text><Text style={styles.id}>@{worker.loginId}</Text></View><View style={{ alignItems: 'flex-end', gap: 5 }}><Text style={worker.mustChangePassword ? styles.waiting : styles.ready}>{worker.mustChangePassword ? '비밀번호 변경 전' : '사용 중'}</Text><Text style={styles.jobCount}>{jobs.filter(j => j.workerIds.includes(worker.id)).length}개 작업</Text></View></Card>) : <Empty title="등록된 작업자가 없습니다" detail="작업자 계정을 추가해주세요." />}</ScrollView><Modal visible={open} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setOpen(false)}><ScrollView style={ui.screen} contentContainerStyle={ui.content}><View style={[ui.row, { justifyContent: 'space-between' }]}><Text style={ui.title}>작업자 추가</Text><Pressable onPress={() => setOpen(false)}><Text style={styles.close}>닫기</Text></Pressable></View><Text style={ui.subtitle}>작업자는 최초 로그인 시 반드시 새 비밀번호를 설정합니다.</Text><Card style={{ gap: 16 }}><Field label="이름 *" value={name} onChangeText={setName} placeholder="작업자 이름" /><Field label="로그인 아이디 *" value={loginId} onChangeText={setLoginId} autoCapitalize="none" placeholder="영문/숫자 아이디" /><Field label="초기 비밀번호 *" value={password} onChangeText={setPassword} secureTextEntry /><Button title="계정 생성" onPress={submit} /></Card></ScrollView></Modal></>;
}
const styles = StyleSheet.create({ add: { backgroundColor: colors.primary, borderRadius: 12, paddingHorizontal: 13, paddingVertical: 10 }, addText: { color: '#fff', fontWeight: '700' }, worker: { flexDirection: 'row', alignItems: 'center', gap: 13 }, avatar: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primary, fontSize: 18, fontWeight: '800' }, name: { color: colors.ink, fontWeight: '700', fontSize: 16 }, id: { color: colors.muted, fontSize: 13, marginTop: 3 }, ready: { color: colors.success, fontWeight: '700', fontSize: 12 }, waiting: { color: colors.warning, fontWeight: '700', fontSize: 12 }, jobCount: { color: colors.muted, fontSize: 12 }, close: { color: colors.primary, fontWeight: '700', fontSize: 16 } });
